### ISSUE TITLE
Fatal error hnsd process keeps crashing

### ISSUE THREAD

**Issue by NetOpWibby** [imperviousinc/fingertip#11]
<img width="328" alt="SS 2021-11-24 at 12 07 05 PM" src="https://user-images.githubusercontent.com/1288356/143306476-6598c243-092e-499c-8202-a65bda99ee10.png">

I'm on:
- macOS Monterey 12.0.1
- M1 Max CPU
- 32GB RAM

**Comment by buffrr** [comment]
There's an another hnsd running likely. Open activity monitor and search for hnsd kill any hnsd processes see if the issue resolves

**Comment by NetOpWibby** [comment]
That was it! Sweet.
