### ISSUE TITLE
HTTPS not working in Linux AppImage

### ISSUE THREAD

**Issue by Snaddyvitch-Dispenser** [imperviousinc/fingertip#15]
![Screenshot from 2021-12-14 17-52-47](https://user-images.githubusercontent.com/28988626/146053003-428de918-914c-4602-97c5-40b6c0c4b20e.png)
![Screenshot from 2021-12-14 17-54-00](https://user-images.githubusercontent.com/28988626/146053185-6fa5ed7f-750c-4fad-b21c-b368b7982ed3.png)

While the Handshake Latest AppImage (v0.0.3) on Zorin 16 (Ubuntu 20.04) the proxy works to resolve domains, but even with the certificate installed in firefox and my PC's trust store, TLS doesn't work

**Comment by Snaddyvitch-Dispenser** [comment]
An addition:

TLS works on https://proofofconcept/, but not https://home.johnnywu/

**Comment by pinheadmz** [comment]
johnnywu is not a signed zone, has no DS record in the root zone and therefore can not be secure. Likely his web server isn't even configured for https
