### ISSUE TITLE
Server failure when attempting to resolve Handshake domains. Wrong Port?

### ISSUE THREAD

**Issue by esuter19** [imperviousinc/fingertip#2]
I just setup Fingertip on my Windows 10 machine according to the video linked on the Impervious' website. When I attempt to visit any Handshake domain I get a 502 Bad Gateway error. The error message alternates intermittently between ```server error``` and ```read udp 127.0.0.1:5xxxx->127.0.0.1:9592: i/o timeout``` where the last four digits of the port have ranged between 1550 and 7650 across different page refreshes. Visiting non-Handshake websites works perfectly fine and attempting to access an invalid Handshake site states that the host does not exist. Attempting to access a Handshake domain securely gives a generic Firefox "unable to connect" error page.

I think the problem has to do with the fact that port 9592 (above) does not match 9590 (the setup webpage), but this is not an area I know a lot about.

My Firefox proxy settings should be correct:
![image](https://user-images.githubusercontent.com/59849377/129797206-62732cb2-3f8c-472b-8203-1fa3668733c3.png)

Running ```netstat -ab``` shows that Fingertip is running on 9590 but nothing is listening on 9592:
```TCP    127.0.0.1:9590         DESKTOP-PM0S2JG:0      LISTENING                                                         [fingertip.exe]```

**Comment by pinheadmz** [comment]
Is hnsd synced? The menu will have a "height" value.

**Comment by buffrr** [comment]
> I think the problem has to do with the fact that port 9592 (above) does not match 9590 (the setup webpage), but this is not an area I know a lot about.

`9590` is the proxy port. hnsd's recursive resolver listens on port `9592` so it seems that hnsd isn't reachable for some reason. You can try stopping and starting fingertip. Look at the height value it should increase (which means hnsd is running) wait a bit for it to sync.

Also, can you try accessing `http://certified.badass`? i'm just checking to see if something is interfering with your DNS since this name uses HIP-5 and resolves a bit differently.

**Comment by esuter19** [comment]
Whoops, didn't realize that it required hnsd as a prerequisite cause it didn't say on the Impervious homepage. Guess I should install that first!

**Comment by buffrr** [comment]
> Whoops, didn't realize that it required hnsd as a prerequisite cause it didn't say on the Impervious homepage. Guess I should install that first!

hnsd isn't a prerequisite! Fingertip manages an hnsd process internally. If you see the block height, it means its likely running. 

Also, I believe `netstat -ab` will show current connections only. You can open powershell and call `Get-Process -Id (Get-NetUDPEndpoint -LocalPort 9592).OwningProcess` you should see the hnsd process name.

For some reason its timing out for you could be a firewall issue or something interfering with your DNS. You can try opening `http://certified.badass` after its synced see if it works. If you have `dig` for windows, you can also try sending queries to hnsd directly like `dig @127.0.0.1 -p 9592 proofofconcept`

**Comment by esuter19** [comment]
Running the Powershell statement you sent revealed that hnsd was listening on 9592. I could resolve ```http://certified.badass```. It turns out that the wifi I was connected to had strict DNS settings in the firewall that were obstructing traffic. Switching to a less strict network solved this problem. I can now resolve all Handshake names, and can do so securely as well.
