### ISSUE TITLE
Include fingertip in user agent

### ISSUE THREAD

**Issue by rithvikvibhu** [imperviousinc/fingertip#23]
Beacon clients have a `beacon` suffix: `/hnsd:1.0.0/beacon`. Can fingertip also say `/hnsd:1.0.0/fingertip`?

**Comment by pinheadmz** [comment]
Both of these should include applicaiton version as well, e.g. `/hnsd:1.0.0/fingertip:0.0.2`

**Comment by buffrr** [comment]
Done thanks!

**Comment by rithvikvibhu** [comment]
Wow that was fast, nice @buffrr!
